version: '3.7'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql
    restart: always
    hostname: mysql
    container_name: mysql
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
    volumes:
      - /opt/mysql/data:/var/lib/mysql
  #      - /opt/mysql/my.cnf:/etc/mysql/my.cnf 编排挂载 MySQL 配置有一点问题
  nacos-mysql:
    image: mysql:5.7.28
    restart: always
    hostname: nacos-mysql
    container_name: nacos-mysql
    ports:
      - 3307:3306
    volumes:
      - /opt/mysql/nacos:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
  nacos:
    image: nacos/nacos-server
    restart: always
    hostname: nacos
    container_name: nacos
    privileged: true
    ports:
      - 8848:8848
    volumes:
      - /opt/mysql/home/nacos.properties:/home/nacos/conf/application.properties
    environment:
      MODE: standalone
  single:
    image: elasticsearch
    container_name: single
    privileged: true
    restart: always
    #    network_mode: single-kibana
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    #      - discovery.type=single-node 这个非集群模式
    #      - discovery.zen.ping.unicast.hosts=192.168.150.21:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/es/single/single.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/es/data/single:/usr/share/elasticsearch/data
      - /opt/es/logs/single:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana
    container_name: kibana
    restart: always
    depends_on:
      - single
    #    network_mode: single-kibana
    ports:
      - 5601:5601
  es-head:
    image: tobias74/elasticsearch-head:6
    container_name: es-head
    #    network_mode: single-kibana
    restart: always
    depends_on:
      - single
    ports:
      - 9100:9100
