version: "3.7"
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
  mysql:
    image: mysql
    restart: always
    hostname: mysql
    container_name: mysql
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
    volumes:
      - ./mysql/data:/var/lib/mysql
  #      - /opt/mysql/my.cnf:/etc/mysql/my.cnf 编排挂载 MySQL 配置有一点问题
  nacos-mysql:
    image: mysql:5.7.28
    restart: always
    hostname: nacos-mysql
    container_name: nacos-mysql
    ports:
      - 3307:3306
    volumes:
      - ./mysql/nacos:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASS: root
  nacos:
    image: nacos/nacos-server
    restart: always
    hostname: nacos
    container_name: nacos
    privileged: true
    ports:
      - 8848:8848
    volumes:
      - ./nacos/conf/nacos.properties:/home/nacos/conf/application.properties
    environment:
      MODE: standalone
  single:
    image: elasticsearch:7.4.2
    container_name: single
    privileged: true
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
#      - ./elasticsearch/single/conf/single.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/single/data:/usr/share/elasticsearch/data
      - ./elasticsearch/single/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
  es-head:
    container_name: es-head
    image: mobz/elasticsearch-head:5
    restart: always
    ports:
      - 9100:9100
    depends_on:
      - single
  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:7.4.2
    privileged: true
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./kibana/conf/kibanasingle.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - elasticsearch.hosts=http://single:9200
    depends_on:
      - single

#  es-master:
#    container_name: es-master
#    hostname: es-master
#    image: elasticsearch:7.4.2
#    restart: always
#    privileged: true
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - ./elasticsearch/master/conf/es-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elasticsearch/master/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/master/logs:/usr/share/elasticsearch/logs
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#
#  es-slave1:
#    container_name: es-slave1
#    image: elasticsearch:7.4.2
#    restart: always
#    privileged: true
#    ports:
#      - 9201:9200
#      - 9301:9300
#    volumes:
#      - ./elasticsearch/slave1/conf/es-slave1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elasticsearch/slave1/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/slave1/logs:/usr/share/elasticsearch/logs
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#
#  es-slave2:
#    container_name: es-slave2
#    image: elasticsearch:7.4.2
#    restart: always
#    privileged: true
#    ports:
#      - 9202:9200
#      - 9302:9300
#    volumes:
#      - ./elasticsearch/slave2/conf/es-slave2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elasticsearch/slave2/data:/usr/share/elasticsearch/data
#      - ./elasticsearch/slave2/logs:/usr/share/elasticsearch/logs
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#
#  es-head:
#    container_name: es-head
#    image: mobz/elasticsearch-head:5
#    restart: always
#    ports:
#      - 9100:9100
#    depends_on:
#      - es-master
#      - es-slave1
#      - es-slave2
#
#  kibana:
#    container_name: kibana
#    hostname: kibana
#    image: kibana:7.4.2
#    privileged: true
#    restart: always
#    ports:
#      - 5601:5601
#    volumes:
#      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
#    environment:
#      - elasticsearch.hosts=http://es-master:9200
#    depends_on:
#      - es-master
#      - es-slave1
#      - es-slave2

#  filebeat:
#    # 容器名称
#    container_name: filebeat
#    # 主机名称
#    hostname: filebeat
#    # 镜像
#    image: docker.elastic.co/beats/filebeat:7.1.1
#    # 重启机制
#    restart: always
#    # 持久化挂载
#    volumes:
#      - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      # 映射到容器中[作为数据源]
#      - ./logs:/home/project/spring-boot-elasticsearch/logs
#      - ./filebeat/logs:/usr/share/filebeat/logs
#      - ./filebeat/data:/usr/share/filebeat/data
#    # 将指定容器连接到当前连接，可以设置别名，避免ip方式导致的容器重启动态改变的无法连接情况
#    links:
#      - logstash
#    # 依赖服务[可无]
#    depends_on:
#      - es-master
#      - es-slave1
#      - es-slave2
#
#  logstash:
#    container_name: logstash
#    hostname: logstash
#    image: logstash:7.1.1
#    command: logstash -f ./conf/logstash-filebeat.conf
#    restart: always
#    volumes:
#      # 映射到容器中
#      - ./logstash/conf/logstash-filebeat.conf:/usr/share/logstash/conf/logstash-filebeat.conf
#    environment:
#      - elasticsearch.hosts=http://es-master:9200
#      # 解决logstash监控连接报错
#      - xpack.monitoring.elasticsearch.hosts=http://es-master:9200
#    ports:
#      - 5044:5044
#    depends_on:
#      - es-master
#      - es-slave1
#      - es-slave2
