version: '3'
services:
  single:
    image: elasticsearch:6.4.3
    container_name: single
    privileged: true
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.zen.ping.unicast.hosts=172.16.159.20:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/es/single/single.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/es/data/single:/usr/share/elasticsearch/data
      - /opt/es/logs/single:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
  es-head:
    image: tobias74/elasticsearch-head:6
    container_name: es-head
    restart: always
    ports:
      - "9100:9100"
#  kibana:
#    image: kibana:6.4.3
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_URL: http://172.16.159.20:9200
#    depends_on:
#      - single
#    restart: always
#    ports:
#      - 5061:5061
