version: '3'
services:
  node1: # 服务名称
    image: elasticsearch
    container_name: node1 # 容器名称
    hostname: node1
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    #      - "discovery.zen.ping.unicast.hosts=172.16.159.20:9301,192.168.150.21:9302,192.168.150.21:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/es/config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/es/data/node1:/usr/share/elasticsearch/data
      - /opt/es/logs/node1:/usr/share/elasticsearch/logs
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    ports:
      - 9200:9200 # 暴露的端口信息和docker run -d -p 80:80一样
      - 9300:9300
  node2:
    image: elasticsearch
    container_name: node2
    hostname: node2
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    #      - "discovery.zen.ping.unicast.hosts=172.16.159.20:9302,172.16.159.20:9301,172.16.159.20:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/es/config/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/es/data/node2:/usr/share/elasticsearch/data
      - /opt/es/logs/node2:/usr/share/elasticsearch/logs
    ports:
      - 9201:9201
      - 9301:9301
  node3:
    image: elasticsearch
    container_name: node3
    hostname: node3
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/es/config/es3.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/es/data/node3:/usr/share/elasticsearch/data
      - /opt/es/logs/node3:/usr/share/elasticsearch/logs
    ports:
      - 9202:9202
      - 9302:9302
  es-head:
    image: tobias74/elasticsearch-head:6
    container_name: es-head
    restart: always
    ports:
      - "9100:9100"
#  kibana:
#    image: kibana
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_URL: http://172.16.159.20:9200
#    restart: always
#    ports:
#      - 5061:5061
#  logstash:
#    image: logstash:6.4.3
#    container_name: logstash
#    volumes:
#      - ./config/conf.d:/etc/logstash/conf.d  #logstash 配文件位置
#      - ./logs/log:/tmp
#    restart: always
#    depends_on:
#        - node1  #后于elasticsearch启动
#    ports:
#      - "7001-7005:7001-7005"
#      - "4560:4560"
#      - "9600:9600"
